set -g mouse on
set-window-option -g mode-keys vi

set-option -g status-left-length 50
set-option -g status-left " #S #[default]"
set-option -g status-right ""

set -g base-index 1

bind q kill-session 
